# Generated by Django 5.2.1 on 2025-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_attachedmedia_alter_basecomment_home_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfile',
            name='data',
            field=models.FileField(default=0, upload_to='comments/files/'),
            preserve_default=False,
        ),
    ]
