# Generated by Django 4.2.22 on 2025-06-10 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_attachedimage_data_alter_attachedfile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_hash', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('user_agent', models.TextField()),
                ('screen_resolution', models.CharField(max_length=20)),
                ('color_depth', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=20)),
                ('timezone_offset', models.IntegerField()),
                ('cookie_enabled', models.BooleanField()),
                ('plugins', models.TextField(blank=True)),
                ('canvas_fp', models.TextField(blank=True)),
                ('webgl_fp', models.TextField(blank=True)),
                ('device_memory', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='data',
            field=imagekit.models.fields.ProcessedImageField(upload_to='comments/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'gif', 'png'])]),
        ),
        migrations.AddField(
            model_name='basecomment',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='comments.userdata'),
        ),
    ]
