# Generated by Django 4.2.22 on 2025-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_userdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
