# Generated by Django 4.2.22 on 2025-06-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_userdata_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='timezone_offset',
            field=models.CharField(max_length=255),
        ),
    ]
