# Generated by Django 5.2.1 on 2025-05-29 15:48

import comments.validators
import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_attachedfile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedimage',
            name='data',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='comments/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'gif', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='data',
            field=models.FileField(upload_to='comments/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt']), comments.validators.validate_file_size]),
        ),
    ]
