# Generated by Django 4.2.22 on 2025-06-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_userdata_alter_attachedimage_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='updated_at',
        ),
    ]
